/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    posts: Post;
    people: Person;
    'press-coverage': PressCoverage;
    videos: Video;
    albums: Album;
    media: Media;
    supporters: Supporter;
    feedback: Feedback;
    assistance: Assistance;
    users: User;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    'press-coverage': PressCoverageSelect<false> | PressCoverageSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    albums: AlbumsSelect<false> | AlbumsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    supporters: SupportersSelect<false> | SupportersSelect<true>;
    feedback: FeedbackSelect<false> | FeedbackSelect<true>;
    assistance: AssistanceSelect<false> | AssistanceSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('bn' | 'en') | ('bn' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: 'bn' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      generateShareImage: TaskGenerateShareImage;
      purgeSubmissions: TaskPurgeSubmissions;
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  category:
    'news' | 'statement' | 'press-conference' | 'article' | 'book-review' | 'organisation' | 'welfare' | 'education';
  publishedAt: string;
  excerpt?: string | null;
  heroImage?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  byline?: {
    name?: string | null;
    affiliation?: string | null;
  };
  featured?: boolean | null;
  /**
   * Generated on publish. Override in SEO → Share image.
   */
  shareImage?: (number | null) | Media;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * cushibir.org legacy id
   */
  legacyId?: number | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  credit?: string | null;
  /**
   * Original URL (legacy import)
   */
  sourceUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  name: string;
  position: string;
  group: 'executive' | 'sub-branch' | 'former';
  term?: string | null;
  /**
   * Lower numbers appear first (সভাপতি = 0)
   */
  order?: number | null;
  photo?: (number | null) | Media;
  department?: string | null;
  hall?: string | null;
  session?: string | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  email?: string | null;
  socials?: {
    facebook?: string | null;
    instagram?: string | null;
    x?: string | null;
    youtube?: string | null;
    telegram?: string | null;
  };
  /**
   * Auto-calculated (%)
   */
  profileCompleteness?: number | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * cushibir.org legacy id
   */
  legacyId?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "press-coverage".
 */
export interface PressCoverage {
  id: number;
  headline: string;
  outlet: string;
  publishedAt: string;
  url: string;
  /**
   * Shown only if the outlet allows it; otherwise a typographic card is used.
   */
  externalImageUrl?: string | null;
  /**
   * cushibir.org legacy id
   */
  legacyId?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  title: string;
  youtubeId: string;
  publishedAt: string;
  featured?: boolean | null;
  /**
   * cushibir.org legacy id
   */
  legacyId?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "albums".
 */
export interface Album {
  id: number;
  title: string;
  date: string;
  description?: string | null;
  photos: (number | Media)[];
  /**
   * Legacy photo ids (import)
   */
  legacyIds?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * ওয়েবসাইটের সমর্থক ফরম থেকে আসা তথ্য। নাম ও যোগাযোগের তথ্য এনক্রিপ্ট করা থাকে।
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supporters".
 */
export interface Supporter {
  id: number;
  /**
   * 🔒 এনক্রিপ্ট করে সংরক্ষিত
   */
  name: string;
  /**
   * 🔒 এনক্রিপ্ট করে সংরক্ষিত
   */
  mobile: string;
  /**
   * 🔒 এনক্রিপ্ট করে সংরক্ষিত
   */
  email?: string | null;
  /**
   * 🔒 এনক্রিপ্ট করে সংরক্ষিত
   */
  facebook?: string | null;
  department:
    | 'bangla'
    | 'english'
    | 'history'
    | 'philosophy'
    | 'islamic_history_culture'
    | 'arabic'
    | 'islamic_studies'
    | 'dramatics'
    | 'persian_language_literature'
    | 'pali'
    | 'sanskrit'
    | 'music'
    | 'bangladesh_studies'
    | 'modern_languages'
    | 'fine_arts'
    | 'physics'
    | 'chemistry'
    | 'mathematics'
    | 'statistics'
    | 'applied_chemistry_chemical_engineering'
    | 'forestry_environmental_sciences'
    | 'jnicar'
    | 'accounting'
    | 'management'
    | 'finance'
    | 'marketing'
    | 'human_resource_management'
    | 'banking_insurance'
    | 'cucba'
    | 'economics'
    | 'political_science'
    | 'sociology'
    | 'public_administration'
    | 'anthropology'
    | 'international_relations'
    | 'communication_journalism'
    | 'criminology_police_science'
    | 'development_studies'
    | 'law'
    | 'zoology'
    | 'botany'
    | 'geography_environmental_studies'
    | 'biochemistry_molecular_biology'
    | 'microbiology'
    | 'soil_science'
    | 'genetic_engineering_biotechnology'
    | 'psychology'
    | 'pharmacy'
    | 'computer_science_engineering'
    | 'electrical_electronic_engineering'
    | 'physical_education_sports_science'
    | 'education_research'
    | 'marine_sciences'
    | 'oceanography'
    | 'fisheries'
    | 'paediatrics'
    | 'community_ophthalmology';
  session: string;
  hall?:
    | (
        | 'alaol'
        | 'af_rahman'
        | 'shahjalal'
        | 'suhrawardy'
        | 'shah_amanat'
        | 'shamsun_nahar'
        | 'shaheed_abdur_rab'
        | 'pritilata'
        | 'deshnetri_khaleda_zia'
        | 'masterda_surja_sen'
        | 'shaheed_farhad_hossain'
        | 'bijoy_24'
        | 'nawab_faizunnesa'
        | 'atish_dipangkar'
        | 'shilpi_rashid_chowdhury_hostel'
        | 'non_resident'
      )
    | null;
  interests?: ('dawah' | 'study' | 'welfare' | 'writing' | 'media' | 'it' | 'culture' | 'sports')[] | null;
  /**
   * 🔒 এনক্রিপ্ট করে সংরক্ষিত
   */
  note?: string | null;
  status: 'new' | 'contacted' | 'active' | 'closed';
  staffNote?: string | null;
  consentAt?: string | null;
  mobileHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * বার্তা ও পরিচয় এনক্রিপ্ট করা থাকে। নাম ছাড়া পাঠানো বার্তায় প্রেরকের কোনো তথ্য সংরক্ষণ করা হয় না।
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback".
 */
export interface Feedback {
  id: number;
  kind: 'advice' | 'ehtesab' | 'complaint';
  /**
   * খালি থাকলে পুরো শাখার উদ্দেশে
   */
  about?: (number | null) | Person;
  subject: string;
  /**
   * 🔒 এনক্রিপ্ট করে সংরক্ষিত
   */
  message: string;
  anonymous?: boolean | null;
  /**
   * 🔒 এনক্রিপ্ট করে সংরক্ষিত
   */
  name?: string | null;
  /**
   * 🔒 এনক্রিপ্ট করে সংরক্ষিত
   */
  contact?: string | null;
  status: 'new' | 'in-review' | 'answered' | 'closed';
  staffNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * আবেদনকারী ট্র্যাকিং আইডি ও গোপন কোড দিয়ে অবস্থা দেখতে পারেন। "আবেদনকারীর জন্য বার্তা" তিনি দেখতে পাবেন।
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assistance".
 */
export interface Assistance {
  id: number;
  trackingId: string;
  type: 'scholarship' | 'medical' | 'other';
  subject?: string | null;
  /**
   * 🔒 এনক্রিপ্ট করে সংরক্ষিত
   */
  name: string;
  /**
   * 🔒 এনক্রিপ্ট করে সংরক্ষিত
   */
  mobile: string;
  /**
   * 🔒 এনক্রিপ্ট করে সংরক্ষিত
   */
  registration?: string | null;
  department:
    | 'bangla'
    | 'english'
    | 'history'
    | 'philosophy'
    | 'islamic_history_culture'
    | 'arabic'
    | 'islamic_studies'
    | 'dramatics'
    | 'persian_language_literature'
    | 'pali'
    | 'sanskrit'
    | 'music'
    | 'bangladesh_studies'
    | 'modern_languages'
    | 'fine_arts'
    | 'physics'
    | 'chemistry'
    | 'mathematics'
    | 'statistics'
    | 'applied_chemistry_chemical_engineering'
    | 'forestry_environmental_sciences'
    | 'jnicar'
    | 'accounting'
    | 'management'
    | 'finance'
    | 'marketing'
    | 'human_resource_management'
    | 'banking_insurance'
    | 'cucba'
    | 'economics'
    | 'political_science'
    | 'sociology'
    | 'public_administration'
    | 'anthropology'
    | 'international_relations'
    | 'communication_journalism'
    | 'criminology_police_science'
    | 'development_studies'
    | 'law'
    | 'zoology'
    | 'botany'
    | 'geography_environmental_studies'
    | 'biochemistry_molecular_biology'
    | 'microbiology'
    | 'soil_science'
    | 'genetic_engineering_biotechnology'
    | 'psychology'
    | 'pharmacy'
    | 'computer_science_engineering'
    | 'electrical_electronic_engineering'
    | 'physical_education_sports_science'
    | 'education_research'
    | 'marine_sciences'
    | 'oceanography'
    | 'fisheries'
    | 'paediatrics'
    | 'community_ophthalmology';
  session: string;
  hall?:
    | (
        | 'alaol'
        | 'af_rahman'
        | 'shahjalal'
        | 'suhrawardy'
        | 'shah_amanat'
        | 'shamsun_nahar'
        | 'shaheed_abdur_rab'
        | 'pritilata'
        | 'deshnetri_khaleda_zia'
        | 'masterda_surja_sen'
        | 'shaheed_farhad_hossain'
        | 'bijoy_24'
        | 'nawab_faizunnesa'
        | 'atish_dipangkar'
        | 'shilpi_rashid_chowdhury_hostel'
        | 'non_resident'
      )
    | null;
  /**
   * 🔒 এনক্রিপ্ট করে সংরক্ষিত
   */
  details: string;
  /**
   * 🔒 এনক্রিপ্ট করে সংরক্ষিত
   */
  references?: string | null;
  status: 'submitted' | 'review' | 'interview' | 'approved' | 'declined';
  /**
   * ট্র্যাকিং পাতায় আবেদনকারী এটি দেখবেন, যেমন সাক্ষাৎকারের সময় ও স্থান।
   */
  publicNote?: string | null;
  staffNote?: string | null;
  statusHistory?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  secretHash?: string | null;
  mobileHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  roles: (
    | 'super-admin'
    | 'admin'
    | 'editor'
    | 'contributor'
    | 'service-desk'
    | 'scholarship-reviewer'
    | 'blood-coordinator'
    | 'event-manager'
    | 'volunteer'
  )[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'generateShareImage' | 'purgeSubmissions' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'generateShareImage' | 'purgeSubmissions' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'press-coverage';
        value: number | PressCoverage;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'albums';
        value: number | Album;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'supporters';
        value: number | Supporter;
      } | null)
    | ({
        relationTo: 'feedback';
        value: number | Feedback;
      } | null)
    | ({
        relationTo: 'assistance';
        value: number | Assistance;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  publishedAt?: T;
  excerpt?: T;
  heroImage?: T;
  content?: T;
  byline?:
    | T
    | {
        name?: T;
        affiliation?: T;
      };
  featured?: T;
  shareImage?: T;
  generateSlug?: T;
  slug?: T;
  legacyId?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  name?: T;
  position?: T;
  group?: T;
  term?: T;
  order?: T;
  photo?: T;
  department?: T;
  hall?: T;
  session?: T;
  bio?: T;
  email?: T;
  socials?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        x?: T;
        youtube?: T;
        telegram?: T;
      };
  profileCompleteness?: T;
  generateSlug?: T;
  slug?: T;
  legacyId?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "press-coverage_select".
 */
export interface PressCoverageSelect<T extends boolean = true> {
  headline?: T;
  outlet?: T;
  publishedAt?: T;
  url?: T;
  externalImageUrl?: T;
  legacyId?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  youtubeId?: T;
  publishedAt?: T;
  featured?: T;
  legacyId?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "albums_select".
 */
export interface AlbumsSelect<T extends boolean = true> {
  title?: T;
  date?: T;
  description?: T;
  photos?: T;
  legacyIds?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  sourceUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supporters_select".
 */
export interface SupportersSelect<T extends boolean = true> {
  name?: T;
  mobile?: T;
  email?: T;
  facebook?: T;
  department?: T;
  session?: T;
  hall?: T;
  interests?: T;
  note?: T;
  status?: T;
  staffNote?: T;
  consentAt?: T;
  mobileHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback_select".
 */
export interface FeedbackSelect<T extends boolean = true> {
  kind?: T;
  about?: T;
  subject?: T;
  message?: T;
  anonymous?: T;
  name?: T;
  contact?: T;
  status?: T;
  staffNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assistance_select".
 */
export interface AssistanceSelect<T extends boolean = true> {
  trackingId?: T;
  type?: T;
  subject?: T;
  name?: T;
  mobile?: T;
  registration?: T;
  department?: T;
  session?: T;
  hall?: T;
  details?: T;
  references?: T;
  status?: T;
  publicNote?: T;
  staffNote?: T;
  statusHistory?: T;
  secretHash?: T;
  mobileHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  tagline?: string | null;
  /**
   * Wrap words in **double asterisks** to highlight them in blue.
   */
  heroIntro?: string | null;
  /**
   * The large photo on the homepage. A wide photo of students works best.
   */
  heroImage?: (number | null) | Media;
  /**
   * Two smaller event photos that float beside the main photo. Falls back to recent albums.
   */
  heroGallery?: (number | Media)[] | null;
  stats?:
    | {
        value: number;
        /**
         * e.g. "+", "/২৬"
         */
        suffix?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  contact?: {
    email?: string | null;
    address?: string | null;
  };
  socials?: {
    facebook?: string | null;
    x?: string | null;
    instagram?: string | null;
    youtube?: string | null;
    telegram?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  tagline?: T;
  heroIntro?: T;
  heroImage?: T;
  heroGallery?: T;
  stats?:
    | T
    | {
        value?: T;
        suffix?: T;
        label?: T;
        id?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        address?: T;
      };
  socials?:
    | T
    | {
        facebook?: T;
        x?: T;
        instagram?: T;
        youtube?: T;
        telegram?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskGenerateShareImage".
 */
export interface TaskGenerateShareImage {
  input: {
    postId: number;
  };
  output: {
    mediaId?: number | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskPurgeSubmissions".
 */
export interface TaskPurgeSubmissions {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'posts';
      value: number | Post;
    } | null;
    global?: string | null;
    user?: {
      relationTo: 'users';
      value: number | User;
    } | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}